name: crossplane
home: https://crossplane.io
sources: []
version: 1.15.1
description: Crossplane is an open source Kubernetes add-on that enables platform teams to assemble infrastructure from multiple vendors, and expose higher level self-service APIs for application teams to consume.
keywords:
    - cloud
    - infrastructure
    - services
    - application
    - database
    - cache
    - bucket
    - infra
    - app
    - ops
    - gcp
    - azure
    - aws
    - alibaba
    - cloudsql
    - rds
    - s3
    - azuredatabase
    - asparadb
    - gke
    - aks
    - eks
maintainers:
    - name: Crossplane Maintainers
      email: info@crossplane.io
      url: ""
icon: https://docs.crossplane.io/android-chrome-192x192.png
apiversion: v1
condition: ""
tags: ""
appversion: 1.17.1
deprecated: false
annotations: {}
kubeversion: ""
dependencies: []
type: ""
